cargo build --package patch-linker

cargo rustc  \
  --package hr  \
  --target aarch64-apple-darwin  \
  -- \
  -C linker=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/patch-linker \

#   Running `CARGO=/Users/jonkelley/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo  \
#   CARGO_BIN_NAME=hr  \
#   CARGO_CRATE_NAME=hr  \
#   CARGO_MANIFEST_DIR=/Users/jonkelley/Development/Tinkering/ipbp/packages/hr  \
#   CARGO_PKG_AUTHORS=''  \
#   CARGO_PKG_DESCRIPTION=''  \
#   CARGO_PKG_HOMEPAGE=''  \
#   CARGO_PKG_LICENSE=''  \
#   CARGO_PKG_LICENSE_FILE=''  \
#   CARGO_PKG_NAME=hr  \
#   CARGO_PKG_README=''  \
#   CARGO_PKG_REPOSITORY=''  \
#   CARGO_PKG_RUST_VERSION=''  \
#   CARGO_PKG_VERSION=0.0.0  \
#   CARGO_PKG_VERSION_MAJOR=0  \
#   CARGO_PKG_VERSION_MINOR=0  \
#   CARGO_PKG_VERSION_PATCH=0  \
#   CARGO_PKG_VERSION_PRE=''  \
#   CARGO_PRIMARY_PACKAGE=1  \
#   DYLD_FALLBACK_LIBRARY_PATH='/Users/jonkelley/Development/Tinkering/ipbp/target/debug/deps:/Users/jonkelley/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/jonkelley/lib:/usr/local/lib:/usr/lib' \
# /Users/jonkelley/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name \
# /Users/jonkelley/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name \
#   hr --edition=2021 packages/hr/src/main.rs \
#   --crate-type bin \
#   --cap-lints allow \
#   -C linker=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/patch-linker \
#   -C embed-bitcode=no -C metadata=f78c3edfafa6f781 -C extra-filename=-f78c3edfafa6f781 \
#   -C debuginfo=0 \
#   --out-dir /Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps \
#   --target aarch64-apple-darwin \
#   -C incremental=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/incremental \
  # -L dependency=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps -L dependency=/Users/jonkelley/Development/Tinkering/ipbp/target/debug/deps --extern anyhow=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libanyhow-9747597cdb5b6acd.rlib --extern bincode=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libbincode-7d242fc5afa36e3d.rlib --extern dioxus=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libdioxus-69ac03163bc40846.rlib --extern include_dir=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libinclude_dir-59ac29f61c6c5502.rlib --extern libc=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibc-f99c99206cb8c8c1.rlib --extern libloading=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibloading-30231bee37ebcae4.rlib --extern macext=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmacext-1fafbb05fa32ce96.rlib --extern memmap=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmemmap-601ee91947edcf4a.rlib --extern object=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libobject-6282850c057aa799.rlib --extern page_size=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libpage_size-953d9be360714ca4.rlib --extern rustc_demangle=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/librustc_demangle-d1af2f9fbb7aa488.rlib --extern serde=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde-e80e1f78481bafe3.rlib --extern serde_json=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde_json-3ab5dc40996e7f84.rlib --extern some_lib=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsome_lib.dylib --extern sysinfo=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsysinfo-00ec3f3a86c88202.rlib --extern tokio=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libtokio-fa09b463ca4b6839.rlib -L native=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/build/objc_exception-1879c54a460cf00f/out \

  # -L dependency=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps -L dependency=/Users/jonkelley/Development/Tinkering/ipbp/target/debug/deps --extern anyhow=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libanyhow-e47e5a1c707a64e8.rlib --extern bincode=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libbincode-7f5c2381b73fdebd.rlib --extern dioxus=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libdioxus-e04a76188c4b96ce.rlib --extern include_dir=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libinclude_dir-eda774a3a9a94fc8.rlib --extern libc=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibc-6ec49819ec41c23b.rlib --extern libloading=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibloading-32f00a7a4dab0b9d.rlib --extern macext=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmacext-5f50122f27bc4fae.rlib --extern memmap=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmemmap-e303563d403375a6.rlib --extern object=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libobject-94c021e5e650e86b.rlib --extern page_size=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libpage_size-c214c4d8a6a05e7b.rlib --extern rustc_demangle=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/librustc_demangle-6a1df267614600ca.rlib --extern serde=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde-ed9758ac063715fb.rlib --extern serde_json=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde_json-797439b97a124062.rlib --extern some_lib=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsome_lib.dylib --extern sysinfo=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsysinfo-1b87fe2bb994128a.rlib --extern tokio=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libtokio-b444b567b8279553.rlib -L native=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/build/objc_exception-c0652ae6923f1283/out \
  # -Z self-profile \
  # -Z time-passes \
  # -Z time-passes \
  # -L dependency=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps \
  # -L dependency=/Users/jonkelley/Development/Tinkering/ipbp/target/debug/deps \
  # -C strip=debuginfo \
  # --extern anyhow=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libanyhow-e47e5a1c707a64e8.rlib --extern bincode=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libbincode-7f5c2381b73fdebd.rlib --extern dioxus=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libdioxus-e04a76188c4b96ce.rlib --extern include_dir=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libinclude_dir-eda774a3a9a94fc8.rlib --extern libc=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibc-6ec49819ec41c23b.rlib --extern libloading=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibloading-32f00a7a4dab0b9d.rlib --extern macext=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmacext-5f50122f27bc4fae.rlib --extern memmap=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmemmap-e303563d403375a6.rlib --extern object=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libobject-94c021e5e650e86b.rlib --extern page_size=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libpage_size-c214c4d8a6a05e7b.rlib --extern rustc_demangle=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/librustc_demangle-6a1df267614600ca.rlib --extern serde=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde-ed9758ac063715fb.rlib --extern serde_json=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde_json-797439b97a124062.rlib --extern some_lib=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsome_lib.dylib --extern sysinfo=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsysinfo-1b87fe2bb994128a.rlib --extern tokio=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libtokio-b444b567b8279553.rlib -L native=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/build/objc_exception-c0652ae6923f1283/out \
  # -Z self-profile \
  # --extern anyhow=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libanyhow-6b0b586214e5cf33.rlib --extern bincode=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libbincode-b30861d94852cb64.rlib --extern dioxus=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libdioxus-5a73d89c45f7ab0e.rlib --extern include_dir=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libinclude_dir-9d7bc21d4f9cd7cc.rlib --extern libc=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibc-6dd57e903337db13.rlib --extern libloading=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibloading-c844f451482be5e3.rlib --extern macext=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmacext-43970219e4a9c956.rlib --extern memmap=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmemmap-ae27ce3cd1498975.rlib --extern object=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libobject-47270fa5d31b9028.rlib --extern page_size=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libpage_size-2e2d8670210f05b5.rlib --extern rustc_demangle=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/librustc_demangle-9e67c0437e258840.rlib --extern serde=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde-46f7e5fa475ef30f.rlib --extern serde_json=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde_json-76c1ba42b9aa4842.rlib --extern some_lib=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsome_lib.dylib --extern sysinfo=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsysinfo-69f7d4635900dbe7.rlib --extern tokio=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libtokio-09062f6d9f021c4f.rlib -L native=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/build/objc_exception-95f01595acf38794/out \
  # -Z threads=32 \
  # -Z time-passes
  # -C relocation-model=static \
  # --extern anyhow=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libanyhow-6b0b586214e5cf33.rlib --extern bincode=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libbincode-b30861d94852cb64.rlib --extern dioxus=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libdioxus-5a73d89c45f7ab0e.rlib --extern include_dir=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libinclude_dir-9d7bc21d4f9cd7cc.rlib --extern libc=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibc-6dd57e903337db13.rlib --extern libloading=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/liblibloading-c844f451482be5e3.rlib --extern macext=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmacext-43970219e4a9c956.rlib --extern memmap=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libmemmap-ae27ce3cd1498975.rlib --extern object=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libobject-47270fa5d31b9028.rlib --extern page_size=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libpage_size-2e2d8670210f05b5.rlib --extern rustc_demangle=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/librustc_demangle-9e67c0437e258840.rlib --extern serde=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde-46f7e5fa475ef30f.rlib --extern serde_json=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libserde_json-76c1ba42b9aa4842.rlib --extern some_lib=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsome_lib.dylib --extern sysinfo=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libsysinfo-69f7d4635900dbe7.rlib --extern tokio=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/deps/libtokio-09062f6d9f021c4f.rlib -L native=/Users/jonkelley/Development/Tinkering/ipbp/target/aarch64-apple-darwin/debug/build/objc_exception-95f01595acf38794/out \
  # --emit=obj \
  # --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=174 \


# https://doc.rust-lang.org/rustc/command-line-arguments.html
