[package]
name = "hr"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
include_dir = "0.7.3"
libc = "0.2.155"
libloading = "0.8.3"
macext = "0.2.1"
object = { version = "0.35.0", features = ["all"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
sysinfo = "0.30.12"
