[package]
name = "cargo-hotreload"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
cargo_metadata = "0.19.1"
# krates = "0.17.5"
clap = { version = "4.5.28", features = ["derive"] }
futures = "0.3.31"
futures-channel = "0.3.31"
futures-util = "0.3.31"
notify = "8.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
shell-words = "1.1.0"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
urlencoding = "2.1.3"
