[package]
name = "object-diff"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
gimli = "0.31.1"
itertools = "0.14.0"
object = { workspace = true }
pretty-hex = "0.4.1"
pretty_assertions = "1.4.1"
