[package]
name = "binary-patch"
version = "0.1.0"
edition = "2021"

[dependencies]
hotreload-macro = { path = "../hotreload-macro" }
dioxus = { workspace = true, features = ["desktop"] }
anyhow = "1.0.86"
bincode = "1.3.3"
include_dir = "0.7.3"
libc = "0.2.155"
libloading = "0.8.3"
macext = "0.2.1"
memmap = "0.7.0"
object = { workspace = true, features = ["all"] }
rustc-demangle = "0.1.24"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
sysinfo = "0.30.12"
page_size = "0.4.2"
tokio = { version = "1.38.0", features = ["full"] }
